import { useCallback, useEffect, useRef, useState } from "react";
import { ask } from "@tauri-apps/plugin-dialog";
import { api, errorMessage } from "../../api/client";
import { MAX_RECOMMENDED_WORDS } from "../../api/constants";
import type { AudioStatus, ItemDetail, LessonDetail } from "../../api/types";
import type { Navigate, Route } from "../../navigation";
import ErrorBanner from "../../components/ErrorBanner";
import LoadingPage from "../../components/LoadingPage";
import AudioGenerationStatus from "./AudioGenerationStatus";
import LessonItemRow from "./LessonItemRow";
import { useAudioGeneration } from "./useAudioGeneration";

interface Props {
  lessonId: string;
  /** Generate missing audio as soon as the lesson has loaded. */
  autoGenerate: boolean;
  navigate: Navigate;
}

export default function LessonScreen({ lessonId, autoGenerate, navigate }: Props) {
  const [detail, setDetail] = useState<LessonDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busyItemIds, setBusyItemIds] = useState<ReadonlySet<number>>(new Set());
  const hasAutoGenerated = useRef(false);

  const refresh = useCallback(async () => {
    try {
      setDetail(await api.getLesson(lessonId));
    } catch (e) {
      setError(errorMessage(e));
    }
  }, [lessonId]);

  useEffect(() => {
    refresh();
  }, [refresh]);

  const updateItem = useCallback((itemId: number, change: Partial<ItemDetail>) => {
    setDetail(
      (d) =>
        d && { ...d, items: d.items.map((i) => (i.id === itemId ? { ...i, ...change } : i)) },
    );
  }, []);

  const showItemStatus = useCallback(
    (itemId: number, audioStatus: AudioStatus) => updateItem(itemId, { audioStatus }),
    [updateItem],
  );
  const generation = useAudioGeneration(lessonId, showItemStatus);
  const { generate } = generation;

  const generateAudio = useCallback(
    async (force: boolean) => {
      setError(null);
      try {
        await generate(force);
      } catch (e) {
        setError(errorMessage(e));
      } finally {
        refresh();
      }
    },
    [generate, refresh],
  );

  useEffect(() => {
    if (!autoGenerate || hasAutoGenerated.current || !detail) return;
    hasAutoGenerated.current = true;
    if (detail.items.some((i) => i.audioStatus !== "ready")) generateAudio(false);
  }, [autoGenerate, detail, generateAudio]);

  async function regenerateAll() {
    const confirmed = await ask(
      "Regenerate audio for every item? This calls Azure once per item.",
      { title: "Regenerate all audio", okLabel: "Regenerate", cancelLabel: "Cancel" },
    );
    if (confirmed) generateAudio(true);
  }

  async function regenerateItem(itemId: number) {
    setError(null);
    setBusyItemIds((ids) => new Set(ids).add(itemId));
    try {
      updateItem(itemId, await api.generateItemAudio(itemId, true));
    } catch (e) {
      setError(errorMessage(e));
    } finally {
      setBusyItemIds((ids) => {
        const remaining = new Set(ids);
        remaining.delete(itemId);
        return remaining;
      });
    }
  }

  if (!detail) {
    return (
      <LoadingPage backLabel="Lessons" onBack={() => navigate({ name: "library" })} error={error} />
    );
  }

  const { lesson, items } = detail;
  const readyCount = items.filter((i) => i.audioStatus === "ready").length;
  const longCount = items.filter((i) => i.tooLong).length;
  const thisRoute: Route = { name: "lesson", lessonId };
  const practiceFrom = (startIndex: number) =>
    navigate({ name: "practice", lessonId, startIndex });

  return (
    <main className="page">
      <button className="link" onClick={() => navigate({ name: "library" })}>
        ← Lessons
      </button>
      <header className="topbar">
        <div>
          <h1>{lesson.title}</h1>
          <div className="muted small">
            {items.length} items · audio {readyCount}/{items.length} ready
          </div>
        </div>
        <div className="actions">
          <button onClick={() => navigate({ name: "settings", back: thisRoute })}>Settings</button>
          <button
            onClick={() => generateAudio(false)}
            disabled={generation.isGenerating || readyCount === items.length}
          >
            Generate missing audio
          </button>
          <button onClick={regenerateAll} disabled={generation.isGenerating}>
            Regenerate all
          </button>
          <button className="primary" onClick={() => practiceFrom(0)}>
            Start practice
          </button>
        </div>
      </header>

      <ErrorBanner message={error} onDismiss={() => setError(null)} />
      <AudioGenerationStatus progress={generation.progress} summary={generation.summary} />

      {longCount > 0 && (
        <div className="banner warn">
          {longCount} {longCount === 1 ? "passage is" : "passages are"} longer than{" "}
          {MAX_RECOMMENDED_WORDS} words. Shorter passages are easier to practice.
        </div>
      )}

      <ol className="item-list">
        {items.map((item, index) => (
          <LessonItemRow
            key={item.id}
            item={item}
            isBusy={busyItemIds.has(item.id)}
            isLessonGenerating={generation.isGenerating}
            onRegenerate={() => regenerateItem(item.id)}
            onPractice={() => practiceFrom(index)}
          />
        ))}
      </ol>
    </main>
  );
}
